# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a84e2dceabc0268ec95585be6e069240170b8e6c272ea736d76bf1b4876dfe777d6bc046f385484aa49951cf1096829362e3a8a3ed16400881bcaeb25388379e

test:
  secret_key_base: 4791c7e52053ae3bdc928a0e3a1a9ad41866c7bc3579ac9d1d335a009a52cde7717cfa819c0b5a93f0b15bf91ba0e774f6be1878e2fb5321d67f030f871de27f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
